### ISSUE TITLE
JavaScript Strings in Interop

### ISSUE THREAD

**Issue by jpsamaroo** [brendanator/jsForth#1]
I am attempting to figure out how to convert a counted string (such as from using s" in a definition) into a JavaScript string so that I can call external JavaScript functions that require strings as input. However, I cannot seem to get it working. Here is what I am trying to do:

`: test123   s" statusTarget" ;`
statusTarget is the ID of an element on the DOM in my test page

`test123`
Two numbers are now on the stack, representing the counted string

`js /document.getElementById{2}`
This pops TOS and NOS, but only returns null (where it should have returned something relating to the found element).

I have checked that document.getElementById('statusText') works in the console, however I cannot manage to get the JS interop code to do the same thing. Browsing through js-interop.js seems to indicate that there isn't currently a function to do this conversion, as there are no examples of how to this in the comments at the top. Other JS functions seem to work as long as they only take numbers as input.

I would have attempted to implement this myself, but I cannot yet figure out how strings are stored in Forth's virtual memory, so I am a bit lost (the address on the stack is always some large negative number). Am I overlooking something or is this not yet implemented?

P.S. Great code by the way! jsForth works really well otherwise.

**Comment by brendanator** [comment]
I've implemented `>js-string` which should convert a counted string to a js string. Then you will be able to do `js /document.getElementById{1}`

The reason that some of the addresses are negative is because there's kind of a virtual address system where user input is offset by `1 << 31` and the data space is not offset. This allows both address spaces to be accessed uniformly

Glad you're liking it. Let me know if you have any other problems or suggestions
